name: CI Build

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml
    with:
      java-version: '22'
    secrets:
      PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
